-- Nic's sub-queries to avoid BINARY person_id problems
(SELECT [person_id] = CONVERT(NVARCHAR(50), [person_id]),
        [gender_concept_id],
        [year_of_birth],
        [month_of_birth],
        [day_of_birth],
        [birth_datetime],
        [race_concept_id],
        [ethnicity_concept_id],
        [location_id],
        [provider_id],
        [care_site_id],
        [person_source_value],
        [gender_source_value],
        [gender_source_concept_id],
        [race_source_value],
        [race_source_concept_id],
        [ethnicity_source_value],
        [ethnicity_source_concept_id]
 FROM omop.cdm_deid_std.[person])

(SELECT [condition_occurrence_id],
        [person_id] = CONVERT(NVARCHAR(50), [person_id]),
        [condition_concept_id],
        [condition_start_date],
        [condition_start_datetime],
        [condition_end_date],
        [condition_end_datetime],
        [condition_type_concept_id],
        [stop_reason],
        [provider_id],
        [visit_occurrence_id],
        [visit_detail_id],
        [condition_source_value],
        [condition_source_concept_id],
        [condition_status_source_value],
        [condition_status_concept_id]
 FROM omop.cdm_deid_std.[condition_occurrence])

(SELECT [device_exposure_id],
        [device_type_concept_id],
        [device_type_concept_code],
        [device_type_concept_name],
        [visit_occurrence_id],
        [visit_detail_id],
        [person_id] = CONVERT(NVARCHAR(50), [person_id]),
        [provider_id],
        [device_concept_id],
        [device_concept_code],
        [device_concept_name],
        [device_source_concept_id],
        [device_source_concept_code],
        [device_source_concept_name],
        [device_source_value],
        [unique_device_id],
        [device_exposure_start_date],
        [device_exposure_start_datetime],
        [device_exposure_end_date],
        [device_exposure_end_datetime],
        [quantity]
 FROM omop.cdm_deid_std.[device_exposure])

(SELECT [procedure_occurrence_id],
        [person_id] = CONVERT(NVARCHAR(50), [person_id]),
        [procedure_concept_id],
        [procedure_date],
        [procedure_datetime],
        [procedure_type_concept_id],
        [modifier_concept_id],
        [quantity],
        [provider_id],
        [visit_occurrence_id],
        [visit_detail_id],
        [procedure_source_value],
        [procedure_source_concept_id],
        [modifier_source_value]
 FROM omop.cdm_deid_std.[procedure_occurrence])

(SELECT [measurement_id],
        [person_id] = CONVERT(NVARCHAR(50), [person_id]),
        [measurement_concept_id],
        [measurement_date],
        [measurement_datetime],
        [measurement_time],
        [measurement_type_concept_id],
        [operator_concept_id],
        [value_as_number],
        [value_as_concept_id],
        [unit_concept_id],
        [range_low],
        [range_high],
        [provider_id],
        [visit_occurrence_id],
        [visit_detail_id],
        [measurement_source_value],
        [measurement_source_concept_id],
        [unit_source_value],
        [value_source_value]
 FROM omop.cdm_deid_std.[measurement])

(SELECT [observation_id],
        [person_id] = CONVERT(NVARCHAR(50), [person_id]),
        [observation_concept_id],
        [observation_date],
        [observation_datetime],
        [observation_type_concept_id],
        [value_as_number],
        [value_as_string],
        [value_as_concept_id],
        [qualifier_concept_id],
        [unit_concept_id],
        [provider_id],
        [visit_occurrence_id],
        [visit_detail_id],
        [observation_source_value],
        [observation_source_concept_id],
        [unit_source_value],
        [qualifier_source_value]
 FROM omop.cdm_deid_std.[observation])

(SELECT [person_id] = CONVERT(NVARCHAR(50), [person_id]),
        [death_type_concept_id],
        [death_type_concept_code],
        [death_type_concept_name],
        [visit_occurrence_id],
        [cause_concept_id],
        [cause_concept_code],
        [cause_concept_name],
        [cause_source_concept_id],
        [cause_source_concept_code],
        [cause_source_concept_name],
        [cause_source_value],
        [death_date],
        [death_datetime]
 FROM omop.cdm_deid_std.[death])

(SELECT [drug_exposure_id],
        [person_id] = CONVERT(NVARCHAR(50), [person_id]),
        [drug_concept_id],
        [drug_exposure_start_date],
        [drug_exposure_start_datetime],
        [drug_exposure_end_date],
        [drug_exposure_end_datetime],
        [verbatim_end_date],
        [drug_type_concept_id],
        [stop_reason],
        [refills],
        [quantity],
        [days_supply],
        [sig],
        [route_concept_id],
        [lot_number],
        [provider_id],
        [visit_occurrence_id],
        [visit_detail_id],
        [drug_source_value],
        [drug_source_concept_id],
        [route_source_value],
        [dose_unit_source_value]
 FROM omop.cdm_deid_std.[drug_exposure])

(SELECT [visit_occurrence_id],
        [person_id] = CONVERT(NVARCHAR(50), [person_id]),
        [visit_concept_id],
        [visit_start_date],
        [visit_start_datetime],
        [visit_end_date],
        [visit_end_datetime],
        [visit_type_concept_id],
        [provider_id],
        [care_site_id],
        [visit_source_value],
        [visit_source_concept_id],
        [admitting_source_concept_id],
        [admitting_source_value],
        [discharge_to_concept_id],
        [discharge_to_source_value],
        [preceding_visit_occurrence_id]
 FROM omop.cdm_deid_std.[visit_occurrence])
