-- Schema for table used by concept mapping file loader used by BlueTree to
-- specify new concept mappings to be loaded into MSDW2

USE leaf_setup; -- TODO: change to scratch schema in MSDW2

CREATE TABLE scratch.concept_map_for_loading
(  
    SOURCE_CONCEPT_CODE VARCHAR(50) NOT NULL,
    SOURCE_CONCEPT_NAME VARCHAR(50) NOT NULL,
    SOURCE_CONCEPT_VOCABULARY_ID VARCHAR(50) NOT NULL,
    VALUE_AS_SOURCE_CONCEPT_CODE BIGINT NOT NULL,
    VALUE_AS_SOURCE_CONCEPT_NAME VARCHAR(255),
    VALUE_AS_SOURCE_CONCEPT_VOCABULARY_ID VARCHAR(50),
    TARGET_CONCEPT_ID BIGINT NOT NULL,
    TARGET_CONCEPT_CODE VARCHAR(50),
    TARGET_CONCEPT_NAME VARCHAR(255),
    TARGET_CONCEPT_VOCABULARY_ID VARCHAR(50),
    TARGET_VALUE_AS_CONCEPT_ID BIGINT,
    TARGET_VALUE_AS_CONCEPT_CODE VARCHAR(50),
    TARGET_VALUE_AS_CONCEPT_NAME VARCHAR(255),
    TARGET_VALUE_AS_CONCEPT_VOCABULARY_ID VARCHAR(50),
    TARGET_VALUE_AS_NUMBER BIGINT,
    TARGET_UNIT_CONCEPT_ID BIGINT,
    TARGET_UNIT_CONCEPT_CODE VARCHAR(50),
    TARGET_UNIT_CONCEPT_NAME VARCHAR(255),
    TARGET_UNIT_CONCEPT_VOCABULARY_ID VARCHAR(50),
    TARGET_QUALIFIER_CONCEPT_ID VARCHAR(50),
    TARGET_QUALIFIER_CONCEPT_CODE VARCHAR(50),
    TARGET_QUALIFIER_CONCEPT_NAME VARCHAR(255),
    TARGET_QUALIFIER_CONCEPT_VOCABULARY_ID VARCHAR(50),
    MAPPING_EQUIVALENCE VARCHAR(50) NOT NULL,
    MAPPING_CREATION_USER VARCHAR(50) NOT NULL,
    MAPPING_CREATION_DATETIME datetime NOT NULL,
    MAPPING_STATUS VARCHAR(50) NOT NULL,
    MAPPING_STATUS_USER VARCHAR(50) NOT NULL,
    MAPPING_STATUS_DATETIME datetime NOT NULL,
    MAPPING_COMMENT VARCHAR(255)
);
